version: '3.8'

services:
  # 1. Database MySQL
  mysql:
    image: mysql:8.0
    container_name: oil_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mật khẩu root (cho môi trường local)
      MYSQL_DATABASE: oil_dw     # Tên database sẽ tự tạo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Giữ lại dữ liệu khi tắt container

  # 2. Metabase (Công cụ vẽ biểu đồ - Tuần 3 mới dùng nhưng cài sẵn luôn)
  metabase:
    image: metabase/metabase
    container_name: oil_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase_internal
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data: